#!/bin/sh

is_linux() { [ "$(uname)" = "Linux" ] }

# Update PATH
export PATH=/usr/local/bin:/usr/local/sbin:$HOME/.composer/vendor/bin:$PATH
export PATH=/usr/local/opt/python@2/bin:$PATH
export PATH=/usr/local/opt/gettext/bin:$PATH
export PATH=/usr/local/opt/ruby/bin:$PATH
export PATH="$(yarn global bin):$PATH"
export PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.config/scripts:$PATH

export XDG_USER_CONFIG_DIR=$HOME/.config

if is_linux; then
    export CHROME_PATH=/usr/bin/google-chrome-stable
fi


# Set language
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


# Default programs
export BROWSER=google-chrome-stable
if is_linux; then
    export TERMINAL="st"
else
    export TERMINAL="iterm"
fi

# Use nvim as editor
export VISUAL=nvim
export EDITOR="$VISUAL"


# Development helpers

# Virtualenvwrapper config
export WORKON_HOME=~/.virtualenvs
# Current user so that it can be used by docker-compose
export CURRENT_UID=$(id -u):$(id -g)

# Use a better command for searching with fzf
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden --ignore-file ~/.config/ripgrep/ignore'

