# Load xresources including customizations
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Keyboard layout
setxkbmap -layout us,ee -option 'grp:shifts_toggle'
# Load keys
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
xbindkeys
# Set keyboard repeat rate
xset r rate 225 30

# Run GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
dbus-update-activation-environment --systemd DISPLAY

# Start our window manager
exec i3

