#
# Executes commands at login pre-zshrc.
#

#
# Utils
#

is_linux() { [ "$(uname)" = "Linux" ] }
is_mac() { [ "$(uname)" = "Darwin" ] }

#
# Applications
#

if is_mac; then
    export BROWSER='open'
else
    export BROWSER='firefox-developer-edition'
fi

if is_linux; then
    export TERMINAL="kitty --single-instance --listen-on unix:/tmp/mykitty -o allow_remote_control=yes"
else
    export TERMINAL="kitty"
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# Monitors, you can easily override them by overriding the environment 
# variables in `~/.zprofile.local` (check readme FAQ for how to do this)
#

export MONITOR_PRIMARY='DVI-D-0'
export MONITOR_SECONDARY='HDMI-1'
export MONITOR_RIGHT=$MONITOR_PRIMARY
export MONITOR_LEFT=$MONITOR_SECONDARY

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi
export LC_ALL='en_US.UTF-8'

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
# Some directories should be added before others because they are dependencies
# of the others
path=(
  /usr/local/{bin,sbin}
  /usr/local/opt/ruby/bin
  $path
)
path=(
  /usr/local/opt/python@2/bin
  /usr/local/opt/gettext/bin
  $HOME/.composer/vendor/bin
  $HOME/.local/bin
  $HOME/dotfiles/bin
  "$(yarn global bin)"
  "$(ruby -e 'print Gem.user_dir')/bin"
  /usr/local/Cellar/maven@3.2/3.2.5/bin
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Package configurations
#

# Virtualenvwrapper config
export WORKON_HOME=~/.virtualenvs
# Current user so that it can be used by docker-compose
export CURRENT_UID=$(id -u):$(id -g)

# Use a better command for searching with fzf
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden --ignore-file ~/.config/ripgrep/ignore'

# Set up Pipedrive Git directory
export PIPEDRIVE_GIT_DIR="$HOME/Devel/Work"

# Kitty terminal
export KITTY_LISTEN_ON=/tmp/mykitty

#
# Java
#

if [ -f /usr/libexec/java_home ]; then
    export JAVA_HOME="$(/usr/libexec/java_home)"
fi

# Android
if [[ -d "/usr/local/share/android-sdk" ]]; then
    export ANDROID_SDK_ROOT=/usr/local/share/android-sdk
    export ANDROID_HOME=/usr/local/share/android-sdk

    path=(
      $path
      $ANDROID_SDK_ROOT/emulator
      $ANDROID_SDK_ROOT/platform-tools
      $ANDROID_SDK_ROOT/build-tools/$(ls $ANDROID_HOME/build-tools | sort | tail -1)
    )
fi

#
# NVM
#

export NVM_DIR="$HOME/.nvm"
# Only set this source in Arch Linux
if [[ -d "/usr/share/nvm" ]]; then
    export NVM_SOURCE="/usr/share/nvm"
fi


#
# Read overrides from zprofile.local
#

[[ -f ~/.zprofile.local ]] && source ~/.zprofile.local

#
# Boot
#

# Start i3 if it makes sense to
[[ -z \$DISPLAY ]] && [[ \$(tty) = /dev/tty1 ]] && exec startx
