#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Helpers {{{

is_mac() { [ "$(uname)" = "Darwin" ] }
is_linux() { [ "$(uname)" = "Linux" ] }

# }}}

# Aliases {{{

# Base
alias cd..='cd ..'
alias sudo='sudo -E'  # Use current user configs

# Programs
alias vim='nvim'
alias v='vim'
alias r='ranger'
alias up='docker-compose up'
alias down='docker-compose down'
alias build='docker-compose build'
# Some times tmux does weird things, this can help vs that
alias takeover='tmux detach -a'

# Transmission
alias tsm-start='transmission-daemon'
alias tsm='transmission-remote -l'
tsm-add() { transmission-remote -a "$1" ;}

# Utils & alternatives
alias ls='colorls --sort-dirs'
alias l='colorls -lA --sort-dirs'
if type bat > /dev/null; then
    alias cat='bat'
fi
if type prettyping > /dev/null; then
    alias ping='prettyping --nolegend'
fi
if type fzf > /dev/null; then
    alias preview="fzf --preview 'bat --color \"always\" {}'"
    export FZF_DEFAULT_OPTS="--bind='ctrl-o:execute(nvim {})+abort'"
fi
if type ncdu > /dev/null; then
    alias du='ncdu --color dark -rr -x --exclude .git --exclude node_modules'
fi
if type tldr > /dev/null; then
    alias help='tldr'
fi
if type hub > /dev/null; then
    alias git='hub'
fi
if is_linux; then
    alias pbcopy='xclip -sel clip'
fi
if is_linux; then
    alias p='sudo pacman'
fi

# }}}
# Plugins {{{

# Load FZF ZSH plugin
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Z
source $HOME/Programs/z/z.sh

# Tab completion for colorls
source $(dirname $(gem which colorls))/tab_complete.sh

# Pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# }}}
# Startup {{{

# Start graphical server if i3 not already running.
if [ "$(tty)" = "/dev/tty1" ]; then
    pgrep -x i3 || exec startx
fi

# }}}
# # Overview {{{
set modelines=3
# Custom folding for this file
# vim:foldmethod=marker:foldlevel=0
# }}}
