# Setup {{{

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# }}}
# Helpers {{{

is_mac() { [ "$(uname)" = "Darwin" ] }
is_linux() { [ "$(uname)" = "Linux" ] }

# }}}
# Aliases {{{

# Base
alias cd..='cd ..'
alias sudo='sudo -E'  # Use current user configs

# Programs
alias vim='nvim'
alias v='vim'
alias r='ranger'
alias up='docker-compose up'
alias down='docker-compose down'
alias build='docker-compose build'
alias dps='docker ps'
# Some times tmux does weird things, this can help vs that
alias takeover='tmux detach -a'

# FZF visited directories (with Z) and cd into it
alias zfz='cd $(z | sed ''1!G;h;$!d'' | awk ''{print $2}'' | fzf --height=40% --layout=reverse)'

# Git
alias g='git'

alias ga='git add'
alias gaa='git add --all'

alias gb='git branch'

alias gc='git commit -v'
alias gc!='git commit -v --amend'
alias gca='git commit -v -a'
alias gca!='git commit -v -a --amend'
alias gco='git checkout'

alias gd='git diff'

alias gl='git pull'
alias glg='git log --stat'
alias glog='git log --oneline --decorate --graph'

alias gm='git merge'

alias gp='git push'

alias gst='git status'

# Transmission
alias tsm-start='transmission-daemon'
alias tsm='transmission-remote -l'
tsm-add() { transmission-remote -a "$1" ;}

# Utils & alternatives
if type colorls > /dev/null; then
    alias ls='colorls --sort-dirs'
    alias l='colorls -lA --sort-dirs'
fi
if type bat > /dev/null; then
    alias cat='bat'
fi
if type prettyping > /dev/null; then
    alias ping='prettyping --nolegend'
fi
if type fzf > /dev/null; then
    alias preview="fzf --preview 'bat --color \"always\" {}'"
    export FZF_DEFAULT_OPTS="
        --bind='ctrl-o:execute(nvim {})+abort' 
        --inline-info
        --color=bg+:#1b2b34,bg:#16242c,spinner:#c594c5,hl:#6699cc
        --color=fg:#c0c5ce,header:#586e75,info:#fac863,pointer:#c594c5
        --color=marker:#fac863,fg+:#c0c5ce,prompt:#c594c5,hl+:#c594c5
    "
fi
if type ncdu > /dev/null; then
    alias du='ncdu --color dark -rr -x --exclude .git --exclude node_modules'
fi
if type tldr > /dev/null; then
    alias help='tldr'
fi
if type hub > /dev/null; then
    alias git='hub'
fi
if is_linux; then
    alias pbcopy='xclip -sel clip'
fi
if is_linux; then
    alias p='sudo pacman'
fi

alias ctags="`brew --prefix`/bin/ctags"

function take() {
  mkdir -p $@ && cd ${@:$#}
}

# Codi
# Usage: codi [filetype] [filename]
codi() {
  local syntax="${1:-javascript}"
  shift
  vim -c \
    "let g:startify_disable_at_vimenter = 1 |\
    set bt=nofile ls=0 noru nonu nornu |\
    hi ColorColumn ctermbg=NONE |\
    hi VertSplit ctermbg=NONE |\
    hi NonText ctermfg=0 |\
    Codi $syntax" "$@"
}

# }}}
# Plugins {{{

# Load FZF ZSH plugin
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh

# Z
source $HOME/Programs/z/z.sh

if type colorls > /dev/null; then
    # Tab completion for colorls
    source $(dirname $(gem which colorls))/tab_complete.sh
fi

# Pyenv
if type pyenv > /dev/null; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

# Apply NVM when moving around
precmd() {
    if [ "$PWD" != "$PREV_PWD" ]; then
        PREV_PWD="$PWD";
        if [ -e ".nvmrc" ]; then
            nvm use;
        fi
    fi
}

# Kitty
kitty + complete setup zsh | source /dev/stdin

# }}}
# Startup {{{

# Start graphical server if i3 not already running.
if [ "$(tty)" = "/dev/tty1" ]; then
    pgrep -x i3 || exec startx
fi

# }}}
# # Overview {{{
set modelines=3
# Custom folding for this file
# vim:foldmethod=marker:foldlevel=0
# }}}
