#!/bin/bash

### BREW + FZF
# upgrade multiple packages at once, async
# mnemonic [B]rew [U]pgrade [P]package

function bup()
{
  local upd=$(brew leaves | eval "fzf ${FZF_DEFAULT_OPTS} -m --header='[brew:update]'")

  if [[ $upd ]]; then
    for prog in $(echo $upd)
    do brew upgrade $prog
    done
  fi
}

bup

