#!/bin/bash

# Prompt to filter running Docker containers using FZF and copy the selected 
# container's ID to the clipboard.
function did()
{
    local containerId=$(docker ps --format 'table {{.ID}}\t{{.Image}}' | eval "fzf ${FZF_DEFAULT_OPTS} -m --header='docker:containerId'" | awk '{print $1}')

    if [ "$containerId" != "CONTAINER" ] && [ "x$containerId" != "x" ]
    then
        echo $containerId | pbcopy
        echo "\"$containerId\" copied to clipboard"
    fi
}

did
