#!/usr/bin/env sh

# set names for spaces
yabai -m space 1 --label i
yabai -m space 2 --label ii
yabai -m space 3 --label iii
yabai -m space 4 --label iv
yabai -m space 5 --label v
yabai -m space 6 --label vi
yabai -m space 7 --label vii
yabai -m space 8 --label viii
yabai -m space 9 --label ix
yabai -m space 10 --label x

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "Hack Nerd Font Mono:Regular:12.0"
yabai -m config status_bar_background_color  0xff16242c
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff82AAff
yabai -m config normal_window_border_color   0xff171717
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                off
yabai -m config mouse_action2                off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10

# Application specific settings
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off
yabai -m rule --add app="^Microsoft AutoUpdate$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Firefox Developer Edition$" title="^Opening .*$" manage=off
yabai -m rule --add app="^Firefox$" title="^Opening .*$" manage=off
yabai -m rule --add app="^Finder$" title="^.*\.app Info$" manage=off
yabai -m rule --add app="Simulator" border=off
yabai -m rule --add app="qemu-system-x86_64" manage=on

echo "yabai configuration loaded.."
