# vim:ft=conf:foldmethod=marker:foldlevel=0
# To reload config, press cmd+ctrl+,
#: Fonts {{{

font_family      Victor Mono Medium
bold_font        Victor Mono Bold
italic_font      Victor Mono Medium Italic
bold_italic_font Victor Mono Bold Italic

font_size 16

adjust_line_height  150%
modify_font strikethrough_position 12px

symbol_map U+f101-U+f27d nonicons

modify_font underline_position 3
modify_font underline_thickness 150%

#: }}}
#: Appearance {{{

cursor_shape beam
cursor_blink_interval 0

draw_minimal_borders yes
inactive_text_alpha 0.7

hide_window_decorations titlebar-only
macos_titlebar_color background
macos_show_window_title_in none

include themes/kanagawa.conf
background_opacity 0.9
background_blur 25

#}}}
#: Behavior {{{

scrollback_lines 20000
enable_audio_bell no

#: }}}
#: Keyboard shortcuts {{{

kitty_mod cmd

open_url_modifiers cmd

map cmd+c        copy_to_clipboard
map kitty_mod+v  paste_from_clipboard
map alt+v  paste_from_clipboard

enabled_layouts Splits,Stack

# Scrolling
map kitty_mod+k scroll_line_up
map kitty_mod+j scroll_line_down
map kitty_mod+u scroll_page_up
map kitty_mod+d scroll_page_down

# Scrollback search
map kitty_mod+/      launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id

map kitty_mod+g combine : launch --location=vsplit --cwd=current zsh -ci "lazygit" : goto_layout Stack

# Scroll to previous/next prompt
map kitty_mod+p scroll_to_prompt -1
map kitty_mod+n scroll_to_prompt 1

# Tabs
map kitty_mod+]     next_tab
map kitty_mod+[     previous_tab
map kitty_mod+t     new_tab_with_cwd
map cmd+t           launch --cwd current --env OPEN_PROJECT=1 --type tab
map kitty_mod+alt+t set_tab_title

#}}}
#: Window management {{{

map kitty_mod+enter new_window_with_cwd

map cmd+enter       no_op
map cmd+enter       new_window_with_cwd
map kitty_mod+enter new_window_with_cwd
map kitty_mod+alt+j move_window_forward
map kitty_mod+alt+k move_window_backward

map kitty_mod+s launch --location=hsplit --cwd=current
map kitty_mod+a launch --location=vsplit --cwd=current

map kitty_mod+o resize_window narrower
map kitty_mod+y resize_window wider
map kitty_mod+u resize_window taller
map kitty_mod+i resize_window shorter

map cmd+equal change_font_size all +0.5
map cmd+minus change_font_size all -0.5

# Split navigation
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right

map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+l

# Toggle between full screen and splits
map kitty_mod+f next_layout

#: }}}
#: Advanced {{{

allow_remote_control yes
listen_on unix:/tmp/kitty

startup_session default_session.kitty

shell_integration enabled no-title

#: }}}
#: Include host specific conf {{{

# A local Kitty configuration file can be created which is not added to Git and 
# can be used to conveniently override settings.
include kitty.local.conf

# }}}
