#!/bin/sh

# Load xresources including customizations
xrdb -merge ~/.config/X11/Xresources

# Change keyboard layout with left + right shift
# Also map the caps lock key to ctrl (`caps:ctrl_modifier`)
setxkbmap -layout us,ee -option 'grp:shifts_toggle' -option caps:ctrl_modifier
# But when it is pressed only once, treat it as escape.
killall xcape 2> /dev/null; xcape -e 'Caps_Lock=Escape'
# Set keyboard repeat rate
xset r rate 225 30

# Run GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
dbus-update-activation-environment --systemd DISPLAY

# Load Nvidia configuration
nvidia-settings --config $DXG_DATA_HOME/.nvidia-settings-rc --load-config-only

# Source scripts from the xinit directory
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Start our window manager
exec i3
