return {
  Default = ':default:',
  kitty = ':kitty:',
  Spotify = ':spotify:',
  Arc = ':arc:',
  Figma = ':figma:',
  Slack = ':slack:',
  RuneLite = ':runescape:',
  Finder = ':finder:',
  ['System Settings'] = ':gear:',
  Linear = ':linear:',
  ['MongoDB Compass'] = ':mongodb:',
  ['Keynote'] = ':keynote:',
  ['Xcode'] = ':xcode:',
  ['Simulator'] = ':xcode:',
  ['Zen'] = ':zen_browser:',
  ['Cursor'] = ':cursor:',
}
