" # Modeline {
" Rules only for this file
" vim: set sw=2 ts=2 sts=2 tw=78 foldmarker={,} foldmethod=marker spell:
" }
" # Environment {

" Polyglot disabled needs to be set before the plugin is loaded because
" otherwise ftdetection is not disabled
let g:polyglot_disabled = ['typescript', 'typescript.tsx', 'jsx', 'jenkins']

" Read plugins
source ~/.vim/plugins.vim

" }
" # Leader {

nnoremap <space> <nop>
let mapleader="\<Space>"
let maplocalleader="\\"

" }
" # Vim UI {

colorscheme OceanicNext

" }
